baseurl = "https://www.vikrantgajria.me/"
title = "Vixrant"

theme = "m10c"

languagecode = "en"

paginate = 20
canonifyurls = true
pygmentsCodeFences = true

googleAnalytics = "UA-117154240-1"

[params]
    author = "Vikrant Gajria"
    description = "An organism that converts coffee into computer language."
    avatar = "images/avatar.jpg"
    keywords = ["portfolio", "blog", "vikrant", "djsce", "gajria", "engineer", "software", "programmer"]

[params.style]
    primaryColor = "#e056fd" # Text and accents
    # darkestColor = "#b7e8f7" # Sidebar color
    # darkColor = "#ffffff" # Background
    # lightColor = "#111" # Font
    # lightestColor = "#000" # Headers

[[params.social]]
    name = "github"
    url = "https://github.com/vixrant/"
[[params.social]]
    name = "gitlab"
    url = "https://gitlab.com/vixrant/"
[[params.social]]
    name = "twitter"
    url = "https://twitter.com/vixrant/"
[[params.social]]
    name = "linkedin"
    url = "https://linkedin.com/in/vikrantgajria/"

[[menu.main]]
    name = "Résumé"
    url = "https://goo.gl/8YszZv"
[[menu.main]]
    name = "Blog"
    url  = "/posts/"
[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "Notes"
    url = "/notes/"
