baseURL = "https://www.vikrantgajria.me/"
languageCode = "en-us"
title = "🧶 Vikrant Gajria"
theme = "hugo-uilite-forked"

googleAnalytics = "UA-117154240-1"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"
