baseurl = "https://www.vikrantgajria.me/"
title = "Vixrant"

theme = "m10c"

languagecode = "en"

paginate = 20
canonifyurls = true

googleAnalytics = "UA-117154240-1"

[params]
    author = "Vikrant Gajria"
    description = "An orgnaism which converts coffee into computer understandable language."
    keywords = "blog,developer,personal"
    info = "Full Stack Developer"
    avatar = "images/avatar.png"

[params.style]
    darkestColor = "#dcdde1" # Sidebar color
    darkColor = "#ffffff" # Background
    primaryColor = "#e84118" # Text and accents
    lightColor = "#111" # Font
    lightestColor = "#000" # Headers

[[params.social]]
    name = "github"
    url = "https://github.com/vixrant/"
[[params.social]]
    name = "gitlab"
    url = "https://gitlab.com/vixrant/"
[[params.social]]
    name = "twitter"
    url = "https://twitter.com/vixrant/"
[[params.social]]
    name = "linkedin"
    url = "https://linkedin.com/in/vikrantgajria/"

[[menu.main]]
    name = "Résumé"
    url = "https://goo.gl/8YszZv"
[[menu.main]]
    name = "Blog"
    url  = "/posts/"
[[menu.main]]
    name = "About"
    url = "/about/"
