baseurl = "http://www.vikrant.ga/"
title = "Vixrant"

theme = "coder"

languagecode = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# disqusShortname = "yourdiscussshortname"

[params]
    author = "Vikrant Gajria"
    description = "An orgnaism which converts coffee into computer understandable language."
    keywords = "blog,developer,personal"
    info = "Full Stack Developer"
    avatarurl = "images/avatar.jpg"
    footercontent = "july-21-2018: New website up! Now hosted on gitlab."

    hideCredits = true
    hideCopyright = true

    googleAnalytics = "UA-117154240-1"


    # Custom CSS
    custom_css = []

    # RTL support
    rtl = false

[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/vixrant/"
[[params.social]]
    name = "Gitlab"
    weight = 2
    url = "https://github.com/vixrant/"
[[params.social]]
    name = "Twitter"
    weight = 3
    url = "https://twitter.com/vixrant/"
[[params.social]]
    name = "LinkedIn"
    weight = 4
    url = "https://www.linkedin.com/in/johndoe/"

[[menu.main]]
    name = "Résumé"
    weight = 1
    url = "https://goo.gl/8YszZv"
[[menu.main]]
    name = "Blog"
    weight = 2
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 3
    url = "/about/"
