baseURL: https://www.vikrantgajria.me/
languageCode: en-us
title: Vikrant Gajria

googleAnalytics: UA-117154240-1

pygmentsuseclasses: true
pygmentscodefences: true

taxonomies:
  tag: tags
  series: series

params:
  author:
    name: Vikrant Gajria
    email: vikrantgajria@gmail.com
    pic: face.jpg

  footer:
    text: Copyright © 2020 Vikrant Gajria

  navbar:
    - text: Blog
      href: /blog
    - text: Contact
      href: /#contact
  